// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using sharp_coders_hackadev.Data;

#nullable disable

namespace sharp_coders_hackadev.Migrations
{
    [DbContext(typeof(SharkBankDbContext))]
    [Migration("20230424131328_SharkBankV202")]
    partial class SharkBankV202
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("sharp_coders_hackadev.Models.Acesso", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("acesso_hash");

                    b.Property<string>("AcessoHashCliente")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("acesso_hash_cliente");

                    b.HasKey("Id");

                    b.HasIndex("AcessoHashCliente");

                    b.ToTable("acessos", (string)null);
                });

            modelBuilder.Entity("sharp_coders_hackadev.Models.Agencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("agencia_id");

                    b.Property<string>("AgenciaNome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("agencia_nome");

                    b.HasKey("Id");

                    b.ToTable("agencias", (string)null);
                });

            modelBuilder.Entity("sharp_coders_hackadev.Models.Cliente", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("cliente_hash");

                    b.Property<bool?>("ClienteAtivo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("cliente_ativo");

                    b.Property<string>("ClienteCelular")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("cliente_celular");

                    b.Property<string>("ClienteCpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)")
                        .HasColumnName("cliente_cpf");

                    b.Property<string>("ClienteEmail")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("cliente_email");

                    b.Property<string>("ClienteNome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("cliente_nome");

                    b.HasKey("Id");

                    b.ToTable("clientes", (string)null);
                });

            modelBuilder.Entity("sharp_coders_hackadev.Models.Conta", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("conta_hash");

                    b.Property<string>("ContaHashCliente")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("conta_hash_cliente");

                    b.Property<int>("ContaIdAgencia")
                        .HasMaxLength(255)
                        .HasColumnType("int")
                        .HasColumnName("conta_id_agencia");

                    b.Property<decimal>("ContaSaldo")
                        .HasColumnType("decimal(15)")
                        .HasColumnName("conta_saldo");

                    b.Property<string>("ContaTipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("conta_tipo");

                    b.HasKey("Id");

                    b.HasIndex("ContaHashCliente");

                    b.HasIndex("ContaIdAgencia");

                    b.ToTable("contas", (string)null);
                });

            modelBuilder.Entity("sharp_coders_hackadev.Models.Endereco", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("endereco_hash");

                    b.Property<string>("EnderecoBairro")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("endereco_bairro");

                    b.Property<int>("EnderecoCep")
                        .HasColumnType("int")
                        .HasColumnName("endereco_cep");

                    b.Property<string>("EnderecoComplemento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("endereco_complemento");

                    b.Property<string>("EnderecoEstado")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)")
                        .HasColumnName("endereco_estado");

                    b.Property<string>("EnderecoHashCliente")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("endereco_hash_cliente");

                    b.Property<string>("EnderecoLogradouro")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("endereco_logradouro");

                    b.Property<int>("EnderecoNumero")
                        .HasColumnType("int")
                        .HasColumnName("endereco_numero");

                    b.HasKey("Id");

                    b.HasIndex("EnderecoHashCliente");

                    b.ToTable("enderecos", (string)null);
                });

            modelBuilder.Entity("sharp_coders_hackadev.Models.Transacao", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("transacao_hash");

                    b.Property<DateTime>("TransacaoData")
                        .HasColumnType("datetime")
                        .HasColumnName("transacao_data");

                    b.Property<string>("TransacaoHashCliente")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("transacao_hash_cliente");

                    b.Property<string>("TransacaoOrigem")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("transacao_origem");

                    b.Property<string>("TransacaoTipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("transacao_tipo");

                    b.Property<decimal>("TransacaoValor")
                        .HasColumnType("decimal (15)")
                        .HasColumnName("transacao_valor");

                    b.HasKey("Id");

                    b.HasIndex("TransacaoHashCliente");

                    b.ToTable("transacoes", (string)null);
                });

            modelBuilder.Entity("sharp_coders_hackadev.Models.Acesso", b =>
                {
                    b.HasOne("sharp_coders_hackadev.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("AcessoHashCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("sharp_coders_hackadev.Models.Conta", b =>
                {
                    b.HasOne("sharp_coders_hackadev.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ContaHashCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("sharp_coders_hackadev.Models.Agencia", "Agencia")
                        .WithMany()
                        .HasForeignKey("ContaIdAgencia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agencia");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("sharp_coders_hackadev.Models.Endereco", b =>
                {
                    b.HasOne("sharp_coders_hackadev.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("EnderecoHashCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("sharp_coders_hackadev.Models.Transacao", b =>
                {
                    b.HasOne("sharp_coders_hackadev.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("TransacaoHashCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });
#pragma warning restore 612, 618
        }
    }
}
