// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using sharp_coders_hackadev.Data;

#nullable disable

namespace sharp_coders_hackadev.Migrations
{
    [DbContext(typeof(SharkBankDbContext))]
    [Migration("20230419233922_InicialCreateDbSharkBank")]
    partial class InicialCreateDbSharkBank
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("sharp_coders_hackadev.Models.Acesso", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ClienteId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("CpfAcesso")
                        .HasColumnType("longtext");

                    b.Property<string>("SenhaAcesso")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("Acessos");
                });

            modelBuilder.Entity("sharp_coders_hackadev.Models.Agencia", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("NomeAgencia")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Agencias");
                });

            modelBuilder.Entity("sharp_coders_hackadev.Models.Cliente", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("AtivoCliente")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("CelularCliente")
                        .HasColumnType("longtext");

                    b.Property<string>("EmailCliente")
                        .HasColumnType("longtext");

                    b.Property<string>("NomeCliente")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("sharp_coders_hackadev.Models.Conta", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("AgenciaId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ClienteId")
                        .HasColumnType("varchar(255)");

                    b.Property<decimal>("SaldoConta")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("TipoConta")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AgenciaId");

                    b.HasIndex("ClienteId");

                    b.ToTable("Contas");
                });

            modelBuilder.Entity("sharp_coders_hackadev.Models.Endereco", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("BairroEndereco")
                        .HasColumnType("longtext");

                    b.Property<int>("CepEndereco")
                        .HasColumnType("int");

                    b.Property<string>("ClienteId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ComplementoEndereco")
                        .HasColumnType("longtext");

                    b.Property<string>("EstadoEndereco")
                        .HasColumnType("longtext");

                    b.Property<string>("LogradouroEndereco")
                        .HasColumnType("longtext");

                    b.Property<int>("NumeroEndereco")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("Enderecos");
                });

            modelBuilder.Entity("sharp_coders_hackadev.Models.Transacao", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ClienteId")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("DataTransacao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TipoTransacao")
                        .HasColumnType("longtext");

                    b.Property<decimal>("ValorTransacao")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("Transacoes");
                });

            modelBuilder.Entity("sharp_coders_hackadev.Models.Acesso", b =>
                {
                    b.HasOne("sharp_coders_hackadev.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("sharp_coders_hackadev.Models.Conta", b =>
                {
                    b.HasOne("sharp_coders_hackadev.Models.Agencia", "Agencia")
                        .WithMany()
                        .HasForeignKey("AgenciaId");

                    b.HasOne("sharp_coders_hackadev.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId");

                    b.Navigation("Agencia");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("sharp_coders_hackadev.Models.Endereco", b =>
                {
                    b.HasOne("sharp_coders_hackadev.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("sharp_coders_hackadev.Models.Transacao", b =>
                {
                    b.HasOne("sharp_coders_hackadev.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId");

                    b.Navigation("Cliente");
                });
#pragma warning restore 612, 618
        }
    }
}
